name: template-python
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bandit
  - benchmark
  - coverage
  - flake8
  - mypy
  - prospector
  - pygal
  - pytest
  - python==3.7
  - numpy
  - nbformat
  - jupyter_client
  - ipykernel
  - pip
  - pip:
    - pip
    - pytest-benchmark
    - pytest-cov
    - tox-conda
    - tox
    - Sphinx

